server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://localhost:3306/doran?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: ssafy
    password: ssafy

  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

  cloud:
    gcp:
      storage:
        credentials:
          location: rd-ssafy-project-ebd0eea46d3e.json
        project-id: rd-ssafy-project
        bucket: ssafy-last-project

jwt:
  secret-key:
  access-token-valid-time:
  refresh-token-valid-time:

#  data:
#    redis:
#      port: 6379
#      host: j9b208.p.ssafy.io
#      password: 'ssafy'
