server:
  port: 8080

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://k9b108.p.ssafy.io:3306/doran?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: ssafy
    password: doran_b108
  #    url: jdbc:mysql://localhost:3306/doran?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
  #    username: ssafy
  #    password: ssafy


  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

  cloud:
    gcp:
      storage:
        credentials:
          location: rd-ssafy-project-ebd0eea46d3e.json
        project-id: rd-ssafy-project
        bucket: ssafy-last-project

jwt:
  secret-key: asdfasdfasdfasdfasdf
  access-token-valid-time: 100000
  refresh-token-valid-time: 10000

oauth:
  kakao:
    api-key: f9a75e5f47148dc0aa986669c29c0d03
    token-uri: https://kauth.kakao.com/oauth/token
    redirect-uri: http://localhost:8080/api/oauth/kakao
    info-uri: https://kapi.kakao.com/v2/user/me

#  data:
#    redis:
#      port: 6379
#      host: j9b208.p.ssafy.io
#      password: 'ssafy'
