server:
  port: 8080
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: doran_b108

spring:
  profiles:
    active: local
  datasource:
    url: jdbc:mysql://k9b108.p.ssafy.io:3306/doran?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
    username: ssafy
    password: doran_b108
  #    url: jdbc:mysql://localhost:3306/doran?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul
  #    username: ssafy
  #    password: ssafy

  rabbitmq:
    host: k9b108.p.ssafy.io
    port: 5672
    username: username
    password: password


  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update

  cloud:
    gcp:
      storage:
        credentials:
          location: rd-ssafy-project-ebd0eea46d3e.json
        project-id: rd-ssafy-project
        bucket: ssafy-last-project
  #        bucket: dorandoran
  data:
    redis:
      port: 6379
      host: k9b108.p.ssafy.io
      password: 'ssafy'

  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  security:
    user:
      password: 11

jwt:
  secret-key: asdfasdfasdfasdfasdfasdasdsadasdasdasdqwvasdvwerfbasdf


oauth:
  kakao:
    api-key: f9a75e5f47148dc0aa986669c29c0d03
    token-uri: https://kauth.kakao.com/oauth/token
    #    redirect-uri: http://localhost:3000/oauth/redirect
    redirect-uri: https://dorandoran.site/oauth/redirect/kakao
    info-uri: https://kapi.kakao.com/v2/user/me
  google:
    api-key: 671776662808-t5ihvqjf6v4nlbdqgihhrecoa4tfgns3.apps.googleusercontent.com
    token-uri: https://oauth2.googleapis.com/token
    #    redirect-uri: http://localhost:3000/oauth/redirect
    redirect-uri: https://dorandoran.site/oauth/redirect/google
    resource-uri: https://www.googleapis.com/oauth2/v2/userinfo
    client-secret: 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

rabbitmq:
  queue:
    model: model.req
    voice: voice.req
    model_res_test: model.res
    voice_res_test: voice.res

auth:
  ignore-url: api/oauth/**, api/user/**, api/profile/login, api/profile, api/wait, api/voice/redis

